services:
  - type: web
    name: image-report-generator
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false